# Generated by Django 5.0.6 on 2024-05-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
